# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hls_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hls_service.proto\x12\x03hls\"\"\n\x0fInitTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"4\n\x10InitTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Q\n\x11\x41\x64\x64SegmentRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0csegment_path\x18\x02 \x01(\t\x12\x15\n\rsegment_index\x18\x03 \x01(\x05\"K\n\x12\x41\x64\x64SegmentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bsegment_url\x18\x03 \x01(\t\"&\n\x13\x46inalizeTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"N\n\x14\x46inalizeTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cplaylist_url\x18\x03 \x01(\t\"%\n\x12\x43leanupTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"7\n\x13\x43leanupTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x02\n\nHLSService\x12\x37\n\x08InitTask\x12\x14.hls.InitTaskRequest\x1a\x15.hls.InitTaskResponse\x12=\n\nAddSegment\x12\x16.hls.AddSegmentRequest\x1a\x17.hls.AddSegmentResponse\x12\x43\n\x0c\x46inalizeTask\x12\x18.hls.FinalizeTaskRequest\x1a\x19.hls.FinalizeTaskResponse\x12@\n\x0b\x43leanupTask\x12\x17.hls.CleanupTaskRequest\x1a\x18.hls.CleanupTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hls_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INITTASKREQUEST']._serialized_start=26
  _globals['_INITTASKREQUEST']._serialized_end=60
  _globals['_INITTASKRESPONSE']._serialized_start=62
  _globals['_INITTASKRESPONSE']._serialized_end=114
  _globals['_ADDSEGMENTREQUEST']._serialized_start=116
  _globals['_ADDSEGMENTREQUEST']._serialized_end=197
  _globals['_ADDSEGMENTRESPONSE']._serialized_start=199
  _globals['_ADDSEGMENTRESPONSE']._serialized_end=274
  _globals['_FINALIZETASKREQUEST']._serialized_start=276
  _globals['_FINALIZETASKREQUEST']._serialized_end=314
  _globals['_FINALIZETASKRESPONSE']._serialized_start=316
  _globals['_FINALIZETASKRESPONSE']._serialized_end=394
  _globals['_CLEANUPTASKREQUEST']._serialized_start=396
  _globals['_CLEANUPTASKREQUEST']._serialized_end=433
  _globals['_CLEANUPTASKRESPONSE']._serialized_start=435
  _globals['_CLEANUPTASKRESPONSE']._serialized_end=490
  _globals['_HLSSERVICE']._serialized_start=493
  _globals['_HLSSERVICE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
